openapi: 3.0.0
info:
  title: Non-blocking Transaction API
  version: 1.0.0
paths:
  /api/v1/topup/initiate:
    post:
      summary: Initiate Top-up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                amount:
                  type: number
                service_provider:
                  type: string
                uuid:
                  type: string
                signed_uuid:
                  type: string
                timestamp:
                  type: string
                currency:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      status:
                        type: string
                      amount:
                        type: number
                      currency:
                        type: string
                      uuid:
                        type: string
                      signed_uuid:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/cashout/initiate:
    post:
      summary: Initiate Cash Out
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                signed_uuid:
                  type: string
                timestamp:
                  type: string
                from_account:
                  type: string
                to_account:
                  type: string
                amount:
                  type: number
                currency:
                  type: string
                notes:
                  type: string
                service_provider:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      status:
                        type: string
                      amount:
                        type: number
                      currency:
                        type: string
                      timestamp:
                        type: string
                      uuid:
                        type: string
                      signed_uuid:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/transaction/status:
    post:
      summary: Check Transaction Status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                signed_uuid:
                  type: string
                timestamp:
                  type: string
                service_provider:
                  type: string
                original_uuid:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      original_uuid:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                      details:
                        type: string
                      last_checked:
                        type: string
                      uuid:
                        type: string
                      signed_uuid:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/user:
    post:
      summary: User Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                service_provider:
                  type: string
                uuid:
                  type: string
                signed_uuid:
                  type: string
                timestamp:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      user_id:
                        type: string
                      fullname:
                        type: string
                      status:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/keys/generate:
    post:
      summary: Generate Keys
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      public_key:
                        type: string
                      private_key:
                        type: string
                      uuid:
                        type: string
                      signed_uuid:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/keys/rotate:
    post:
      summary: Rotate Keys
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      new_public_key:
                        type: string
                      new_private_key:
                        type: string
                      uuid:
                        type: string
                      signed_uuid:
                        type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        message:
          type: string
        details:
          type: string
        timestamp:
          type: string
        uuid:
          type: string
        signed_uuid:
          type: string